#!/bin/bash


REGEX='\([0-9]*\)_TCP=tcp://\([0-9]\{1,3\}\.\)\{3\}\([0-9]\)\{1,3\}\:\([0-9]*\)'

env | grep -o $REGEX | sed -e "s/_TCP=tcp:\/\// /" -e "s/:/ /" | awk '{ printf "HiddenServicePort %s %s:%s\n", $1, $2, $3 }' >> /etc/torrc

echo `tail /etc/torrc`

/bin/sleep 5 && /bin/show-serverlink &

/usr/local/bin/tor -f /etc/torrc
